### ISSUE TITLE
about running the examples

### ISSUE THREAD

**Issue by dengbo** [jonathan-beard/RaftLib#12]
hi, I clone all the project from the github and compile the project, but I still can't make the examples, I want to know if the examples don't match the api now?

**Comment by jonathan-beard** [comment]
The examples still match the API. In fact, I haven't pushed the changes yet since I'm determined to get all the examples set up with the CI setup. 

I suspect what you're having a problem with is the linking to Boost (if your error message has something like "can't find demangle.h" then this is the case, if not skip this paragraph and go to the next). The CMake script downloads the boost repo, however the examples that are in the examples folder didn't have the correct include path, nor had they been updated with the pkg-config since I'm in the process of deleting the Makefiles and adding CMakeLists for them.

If you're still having issues with the build then perhaps some other linker path is incorrect. Is the archive that building raft produces available somewhere in the system path (i.e., has it been installed?). The second thing I'd check is the location of the headers, they also must be in the include path, whereas the current example Makefile assumes that all the headers are located within the global include path (i.e. /usr/local/include) or something similar. 

If none of these seems to help, could you copy the output of the cmds you've used to build the examples, and the subsequent error messages? Also, if you could, give me the type of machine (OS, hardware type, etc.). On a linux machine you can simply give me the output of
```bash
uname -a
```

Thanks!

**Comment by dengbo** [comment]
thanks for your comment.
"ThinkPad-Edge-E430c 3.2.0-96-generic #136-Ubuntu SMP Mon Nov 30 21:40:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux" is the result of the command of "uname -a".
I pull the latest code so far and rebuild the project, when I make the cppalgo/search example, I get some error, the output is as following:
g++ -Ofast -mtune=native   -I../../../boost-dep/core/include/ -I../../../boost-dep/config/include/ -Wall -std=c++11 -DRDTSCP=1   -c -o bmh.o bmh.cpp
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from bmh.cpp:27:
/usr/include/c++/4.9/bits/stl_algo.h: In instantiation of ‘_ForwardIterator1 std::__search(_ForwardIterator1, _ForwardIterator1, _ForwardIterator2, _ForwardIterator2, _BinaryPredicate) [with _ForwardIterator1 = raft::chunk_iterator<256ul>; _ForwardIterator2 = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; _BinaryPredicate = __gnu_cxx::__ops::_Iter_equal_to_iter]’:
/usr/include/c++/4.9/bits/stl_algo.h:4023:47:   required from ‘_FIter1 std::search(_FIter1, _FIter1, _FIter2, _FIter2) [with _FIter1 = raft::chunk_iterator<256ul>; _FIter2 = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >]’
bmh.cpp:51:53:   required from ‘raft::kstatus search<T>::run() [with T = raft::filechunk<256ul>]’
bmh.cpp:96:1:   required from here
/usr/include/c++/4.9/bits/stl_algo.h:233:14: error: use of deleted function ‘raft::chunk_iterator<256ul>& raft::chunk_iterator<256ul>::operator=(const raft::chunk_iterator<256ul>&)’
    __current = __first1;
              ^
In file included from /usr/local/include/raftinc/fileio.tcc:30:0,
                 from /usr/local/include/raftio:3,
                 from bmh.cpp:22:
/usr/local/include/raftinc/chunkiterator.tcc:33:37: note: ‘raft::chunk_iterator<256ul>& raft::chunk_iterator<256ul>::operator=(const raft::chunk_iterator<256ul>&)’ is implicitly declared as deleted because ‘raft::chunk_iterator<256ul>’ declares a move constructor or move assignment operator
 template < std::size_t size > class chunk_iterator : public std::iterator< std::forward_iterator_tag, char >
                                     ^
make: *** [bmh.o] Error 1
I search the problem in stackoverflow, and get the similar problem "http://stackoverflow.com/questions/5966698/error-use-of-deleted-function", I'm not sure if these two is really the same.
expect your answer, thanks.

**Comment by dengbo** [comment]
By the way, I have installed the boost, "Boost version: 1.59.0".

**Comment by jonathan-beard** [comment]
Should be fixed now.....looks like there was an issue with a move operator, and a few issues left over from the conversion to CMake. The examples will build now, will change over the examples to CMake this weekend so the dependencies will be updated automatically. At the moment the boost libs are tied in directly (as in, you might need to update the Makefile with the location of boost...or use pkg-config). If you don't have boost installed, the cmake build script will automatically download it into boost-dep and thats what the Makefile is currently pointed at. If its already installed, you'll have to point it to your location since the CMake script won't install boost automatically for you.

**Comment by dengbo** [comment]
thanks very much, the examples can all be compiled, great job

**Comment by jonathan-beard** [comment]
no problem
