### ISSUE TITLE
Need to support non-POD pointers such as smart pointers

### ISSUE THREAD

**Issue by kcleung** [jonathan-beard/RaftLib#9]
RaftLib is an actor-oriented framework for stream processing, and one of the most important applications are video stream processing, which uses data structures such as cv::Mat from OpenCV or similar data structures, that use non-POD pointers such as smart pointers within the structure.

However, as illustrated in Issue #4, currently non-POD pointers are not supported and the presence of such in objects in queues will cause segfault.

This makes raftlib unusable in any substantial applications that involves complex data structures, and is a shopstopper for RaftLib.  Therefore we need to add support of non-POD pointers to RaftLib as top priority

**Comment by jonathan-beard** [comment]
Fixed for allocate function, leaving open until the push function supports them....the network links will require serialization of all internal state too which complicates matters a bit. Maybe transmitting json objects might be the best play here.

**Comment by kcleung** [comment]
I have just read the code in testsuite/testraft10.cpp.  Looks like there has been some large API changes.

Am I correct to say that in order to allocate an object that is to be sent through the pipeline, one needs to use the template allocate API?

auto &foo(output["output_port"].template allocate<T>);

which allocate the object specifically for the port, am I correct?

Then when we want to push the object into output_port, we need to use send() instead of push() in the documentation.

In display::run() in testraft10.cpp, you use:
auto &frame( input[ "0" ].template peek< cvm >() );
to get the frame from the queue.  In this particular example, because the class display no longer needs the object, so it can call the manual destructor of the cv::Mat object release() to release the matrix memopry, then call recycle() to recycle the shallow object?  Here I am confused.

Also suppose if I have a kernel that does something in-place in the object and then resend it, then how can I push an existing object that I got from the input port into the output port, without allocating a new object?

**Comment by jonathan-beard** [comment]
Hi Well, allocate has always been a template function. The allocate and
peek calls as written won't require the "template" keyword, however if you
write them as I should have originally (I re-wrote it quickly to get the
test case out) then it looks something like this:

auto &frame( output[ "0" ].template allocate< T >() );
 The template keyword is required since the allocate call is a dependent
template function (dependent on the class template parameter T). If you use
gcc only then the compiler is smart enough to figure this out (same for
icc). Technically this is incorrect behavior from gcc/icc but at this point
it's pretty much standard (despite not being standard). If you instead use
the type directly "cvm" as in the test case I sent then you can get rid of
the template keyword since you're no longer dependent on the class template
type.

The reason behind needing to call release is that the cv::Mat object needs
to have its internal reference count decremented. It won't naturally be
released since the memory that the cv::Mat object occupies is persistent
(i.e., it's pre-allocated by the run-time and basically the same space is
used over and over). The release call decrements the internal reference
counter so that the destructor is explicitly called. Eventually I'll set it
up so that the run-time calls the destructor on object types. Basically the
point is that the recycle call releases the memory back to the run-time
whereas the release call is openCV specific (to decrement the object
correctly. Perhaps I'll have to go ahead and make the recycle a template
function so that it'll call the destructor on the memory without the
explicit call to release.

So if you want to push an existing object (i.e., allocate one on the stack)
then it'll have to be by copy. The reason being is this would be impossible
to otherwise do since the memory isn't really valid once we move pass the
current stack frame (and we'd have to add locks for each object on the
stack). Moving an object from the input port to the output port directly is
something I'm working on doing efficiently. The copy itself is actually
fairly low overhead since the memory doesn't have to be allocated, it's
technically always there. The only difference is that with non-POD types
the constructor must be called on the memory before it's suitable for use
(set up variables, locks, etc. whatever the constructor does). What we're
looking at doing is setting up a memory pool that can be used to pass
objects / structs / etc. around within a shared memory machine, however
this gets more complicated (basically can't be used) when moving to
accelerators and going over TCP links...these require contiguous memory.
So, it's coming and the method I have in mind won't change the interface at
all. The push call will be able to be used so that you can allocate from
the source kernel and basically push the object through the pipeline. Just
haven't had a chance to implement this yet.

I'll write a longer reply when I have a chance. Perhaps I need to cover
more of this in the wiki. In either case, thanks for the comments!!

**Comment by jonathan-beard** [comment]
k, closing this one as solved for the moment....I'll update the docs to reflect what we've discussed. In the interim you might also want to check out testraft11.cpp in the testsuite. Sometime this week (or perhaps while I'm traveling next week) I'll get around to adding an examples folder for OpenCV. I also need to get a higher frame rate source so I can get past 30fps for the edge detection.

**Comment by jonathan-beard** [comment]
Ok, so I changed the API a bit now with respect to the recycle function so that it will call the appropriate version of recycle so that the run-time itself will call the correct destructor for the port allocated object type. The next step is how to best provide objects that are persistent across streams that can essentially be passed by reference, but mutable.

**Comment by kcleung** [comment]
Okay...... consider this kernel, which takes in an object that has non-POD pointers inside, modify it in place and push the same object:

template <typename T> class Work :: public raft::kernel {
public:
    Work() {
        input.addPort<T>("input");
        output.addPort<T>("output");
    }

    virtual raft::kstatus run() {
        auto &img(input["input"].template peek< T >() );
        // HELP ME how can I declare output so that the same object is put onto the output port?

        do_some_work(img);   // in-place modifications of the img object

        // HELP ME  what do I need to do here to pop the input port?
    }
}

Now I have two questions:

* how can I declare the output so that I push the same object I got from the input port back onto the output port without any memory copying?

* In this case, what do I need to do to let the input port reuse the slot?  Do I still call unpeek() and/or recycle()?  I am confused.

**Comment by jonathan-beard** [comment]
So...short answer, full support is coming for passing the same memory location around. To make this efficient, the run-time must make a decision based on the size and type of the object. Currently the best way to pass an object allocated in one kernel to another is through pointers or smart pointers to heap allocated (notice I said heap, not stack) allocated objects. You can also use smart pointers to wrap these objects in so that you don't have to worry so much about memory management. 

Long term, I think a better solution is to provide transparent "smart objects," which are passed from one port to the next and allocated from a single pool of memory set up by the run-time. This particular feature hasn't been implemented yet, but is on the drawing board. Smart pointers, and simple "dump" pointers can provide this functionality though until the full native solution is finished (hopefully sometime next week).

So to answer your questions directly:
* How can I declare the output so that I push the same object I got from the input port back onto the output port without any memory copying?

>Currently pointers, or smart pointers, to objects that are allocated on the heap. Long 
>term, this will be supported natively within the runtime.

*In this case, what do I need to do to let the input port reuse the slot? Do I still call unpeek() and/or recycle()? I am confused.

>unpeek - call after peek to let the runtime know that all references to the returned value are no longer in use. Keeps the memory location in a valid state for that input port, i.e., it doesn't release the memory location so that the next call to peek will return the same exact location. A call to recycle will release the memory, or invalidate it.

>recycle - so you want to ignore some items from the input stream without ever even looking at them, then this is the function for you. It is also used with the peek call in order to invalidate or free memory to the queue so that the next peek or pop operation will see a a different location.

Does that make sense? If not, I'll update the docs further. Thanks!

**Comment by kcleung** [comment]
Okay.... so should the code look like:

    template <typename T> class Work :: public raft::kernel {
    public:
        Work() {
            input.addPort<T>("input");
            output.addPort<T>("output");
        }

        virtual raft::kstatus run() {
            auto &img(input["input"].template peek< T >() );
    
            do_some_work(img);   // in-place modifications of the complex img object
        
            output["output"].push(img);
            input["input"].recycle();
        }
    }

**Comment by jonathan-beard** [comment]
<h4>how about this:</h4>
```cpp
template <typename T> class Work : public raft::kernel {
public:
    Work() {
        input.addPort<T>("input");
        output.addPort<T>("output");
    }

    virtual raft::kstatus run() 
    {
        auto &img(input["input"].template peek< T >() );

        do_some_work(img);   // in-place modifications of the complex img object

        output[ "output" ].push(img);
        input[ "input" ].unpeek();
        input[ "input" ].recycle( img );
    }
}
```

It might be useful though, since we're still at the early stages of making the peek function return an object which scopes the data element pointed to by img so that the equivalent of "unpeek" is called as the object exits the calling scope similar to the way smart pointers and the current allocate_s function work.

**Comment by jonathan-beard** [comment]
fixed....added smart allocation for external pointers so that anything larger than the L1D cache line size is allocated externally and passed around. garbage collection at each kernel ensures no null references (i.e., user still calls recycle, but it only deallocates the space the pointer occupies, not the actual object being pointed to). This makes passing around larger data structures far more efficient. Eventually I'll add back in the smart memory allocator. Playing with hwloc to provide cross platform support rather than Linux only.
